ALTER TABLE monitors ADD COLUMN mute_until INTEGER;
ALTER TABLE monitors ADD COLUMN headers TEXT;
ALTER TABLE monitors ADD COLUMN nag_min INTEGER NOT NULL DEFAULT 0;
ALTER TABLE monitors ADD COLUMN last_nag_at INTEGER;

ALTER TABLE jobs ADD COLUMN mute_until INTEGER;
ALTER TABLE jobs ADD COLUMN nag_min INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN last_nag_at INTEGER;
